name: 'Github Changelog'
description: 'Generate Changelog based on jira issues'
author: 'Eli Lasry'
runs:
  using: "composite"
  steps:
    - name: Install script dependencies
      run: pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
      shell: bash

    - name: Install script dependencies
      run: git fetch --tags
      shell: bash

    - name: Run python script
      id: changelog
      run: python ${GITHUB_ACTION_PATH}/release_notes.py --from-version ${{ inputs.from_version }} --to-version ${{ inputs.to_version }} --jira-token '${{ inputs.jira_token }}'
      shell: bash

    - name: Generate changelog
      id: changelog_final
      shell: bash
      run: |
        log=$(cat ${{ steps.changelog.outputs.change_log_file }})
        log="${log//'%'/'%25'}"
        log="${log//$'\n'/'%0A'}"
        log="${log//$'\r'/'%0D'}"
        echo "::set-output name=changelog::$log"

    - name: Print empty var
      shell: bash
      run: echo empty? - ${{ steps.changelog.outputs.empty }}

    - name: Print log
      shell: bash
      run: |
        log=$(cat << "EOF"
        ${{ steps.changelog_final.outputs.changelog }}
        EOF
        )
inputs:
  from_version:
    description: "From Tag Version"
    required: true
  to_version:
    description: "To Tag Version"
    required: true
  jira_token:
    description: "Jira token"
    required: true
outputs:
  change_log_file:
    description: "name of file with release notes output"
    value: "${{steps.changelog.outputs.change_log_file}}"
  change_log_file_without_issues:
    description: "name of file with release notes output"
    value: "${{steps.changelog.outputs.change_log_file_without_issues}}"
  changelog:
    description: "All commits titles from jira"  #output without new lines
    value: "${{steps.changelog_final.outputs.changelog}}"
  empty:
    description: "Is the changelog empty?"
    value: "${{steps.changelog.outputs.empty}}"